name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Check Java version
        run: java -version

      - name: Check Maven version
        run: mvn -version

      - name: Build and test
        run: mvn clean verify

      - name: Package application
        run: mvn package -DskipTests

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar


